### ISSUE TITLE
Expand struct fields in default string

### ISSUE THREAD

**Issue by bryceschober** [go-task/slim-sprig#1]
How would I expand struct fields in a `default` string value? In the context of `go-task`, I was trying something like:
```yaml
version: 3

vars:
  DATE:
    sh: date +%Y%m%d

tasks:
  print-test:
    vars:
      LABEL: >-
        {{default "latest-{{.DATE}}" .LABEL}}
    silent: true
    cmds:
      - echo "label '{{.LABEL}}'"
```
Which results in behavior like this:
```shell
$ task print-test
label 'latest-{{.DATE}}'
$ task print-test LABEL=hello
label 'hello'
```
So the usage of `{{default}}` is working, but it's not expanding in the default string value.

**Comment by andreynering** [comment]
Hi @bryceschober,

That's by design. You could do something like this instead:

```yaml
version: 3

vars:
  DATE:
    sh: date +%Y%m%d

tasks:
  print-test:
    vars:
      LABEL: >-
        {{if .LABEL}}{{.LABEL}}{{else}}latest-{{.DATE}}{{end}}
    silent: true
    cmds:
      - echo "label '{{.LABEL}}'"
```
